"""active->status

Revision ID: bf127208e694
Revises: ee4d36026ce4
Create Date: 2026-03-19 10:39:39.347386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf127208e694'
down_revision: Union[str, Sequence[str], None] = 'ee4d36026ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler', sa.Column('status', sa.Enum('ACTIVE', 'FAILED', 'COMPLETED', name='scheduler_status_enum'), nullable=True))
    op.drop_column('scheduler', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler', sa.Column('active', postgresql.ENUM('ACTIVE', 'FAILED', 'COMPLETED', name='scheduler_status_enum'), autoincrement=False, nullable=True))
    op.drop_column('scheduler', 'status')
    # ### end Alembic commands ###
