"""initial tables

Revision ID: f8bfdd39f0f6
Revises: 
Create Date: 2026-03-16 00:06:58.070842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8bfdd39f0f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_callback_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('callback_url', sa.String(length=255), nullable=True),
    sa.Column('callback_headers', sa.JSON(), nullable=True),
    sa.Column('callback_timeout_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_callback_data_id'), 'scheduler_callback_data', ['id'], unique=False)
    op.create_index(op.f('ix_scheduler_callback_data_name'), 'scheduler_callback_data', ['name'], unique=False)
    op.create_table('scheduler_webhook_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('webhook_url', sa.String(length=255), nullable=False),
    sa.Column('webhook_headers', sa.JSON(), nullable=True),
    sa.Column('webhook_timeout_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_webhook_data_id'), 'scheduler_webhook_data', ['id'], unique=False)
    op.create_index(op.f('ix_scheduler_webhook_data_name'), 'scheduler_webhook_data', ['name'], unique=False)
    op.create_table('scheduler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('callback_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schedule_type', sa.Enum('ONCE', 'DAILY', 'WEEKLY', 'MONTHLY', name='schedule_type_enum'), nullable=False),
    sa.Column('repeat_on', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('max_retry', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['callback_id'], ['scheduler_callback_data.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['scheduler_webhook_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_id'), 'scheduler', ['id'], unique=False)
    op.create_index(op.f('ix_scheduler_next_executed_at'), 'scheduler', ['next_executed_at'], unique=False)
    op.create_table('parent_scheduler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scheduler_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scheduler_id'], ['scheduler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_scheduler_scheduler_id'), 'parent_scheduler', ['scheduler_id'], unique=False)
    op.create_table('schedule_callback_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduler_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scheduler_id'], ['scheduler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_task_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduler_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scheduler_id'], ['scheduler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_task_executions')
    op.drop_table('schedule_callback_executions')
    op.drop_index(op.f('ix_parent_scheduler_scheduler_id'), table_name='parent_scheduler')
    op.drop_table('parent_scheduler')
    op.drop_index(op.f('ix_scheduler_next_executed_at'), table_name='scheduler')
    op.drop_index(op.f('ix_scheduler_id'), table_name='scheduler')
    op.drop_table('scheduler')
    op.drop_index(op.f('ix_scheduler_webhook_data_name'), table_name='scheduler_webhook_data')
    op.drop_index(op.f('ix_scheduler_webhook_data_id'), table_name='scheduler_webhook_data')
    op.drop_table('scheduler_webhook_data')
    op.drop_index(op.f('ix_scheduler_callback_data_name'), table_name='scheduler_callback_data')
    op.drop_index(op.f('ix_scheduler_callback_data_id'), table_name='scheduler_callback_data')
    op.drop_table('scheduler_callback_data')
    # ### end Alembic commands ###
